config/routes.rb
Rails.application.routes.draw do
root "jobs#index"      
get 'candidates/signup'
post 'candidates/signup_create'
get 'jobs/new'

match "signin" => "candidates#signin", as: :signin, via: [:get, :post]
get 'candidates/signout'
get 'candidates/profile'
resources :jobs do
resources :candidates do
member do
post 'apply'
end
end
end
  

end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
has_secure_password
has_many :candidates_jobs
has_many :jobs, through: :candidates_jobs

validates :first_name, presence: true 


  def self.authenticate(email,password)
    candidate = find_by_email(email)
    candidate1 = find_by_password(password)
    return candidate if candidate && candidate1
  end 
  
   def applied_job(job)
      if CandidatesJob.where(candidate_id: id, job_id: job).present?
        return true
      else
        return false
      end 
  end
    
 end

app/models/candidates_job.rb
class CandidatesJob < ActiveRecord::Base
    belongs_to :candidate
    belongs_to :job
end

app/models/job.rb
class Job < ActiveRecord::Base
    has_many :candidates_jobs
has_many :candidates, through: :candidates_jobs
 self.per_page = 4
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception 
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :require_login, only: [:apply]
  def signup
    @candidate = Candidate.new
  end
  def signup_create
    if request.post?
      @candidate = Candidate.new(params[:candidate].permit(:first_name, :last_name, :email, :password, :password_confirmation))
     if @candidate.save
      redirect_to "/signin"
     else
      render "candidates/signup"
     end
    end 
  end   
  def signin
    if request.post?
      @candidate = Candidate.find_by(email: params[:candidate][:email])
      if @candidate && @candidate.authenticate(params[:candidate][:password])
       session[:candidate] = @candidate.id
       redirect_to "/jobs"
       else
        render 'signin'
       end
    end       
  end 
  
  def apply
    CandidatesJob.create(:candidate_id => params[:id], :job_id => params[:job_id])
    redirect_to jobs_path
  end
  
   def profile
    candidate=session[:candidate]
    
    @candidate = Candidate.find_by_id(candidate)
  
    @jobs_count=@candidate.jobs.count
   
  end
  
  def signout
    session[:candidate]=nil 
    redirect_to "/jobs"
  end
  
 
  private
  def require_login
    unless session[:candidate]
      flash[:notice]= "login first"
      redirect_to "/signin"
    end
  end  
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @jobs = Job.all
    if session[:candidate].present?
      @candidate = Candidate.find(session[:candidate])
    else
      @candidate = nil
    end
  end
  
  def new
      @job=Job.new
  end
  def create
      @job=Job.new(job_params)
      @job.save
      redirect_to jobs_path
  end
  
  def show
    @job = Job.find(params[:id])
  end
  def edit
  end
  
  private
  def job_params
      params.require(:job).permit(:title, :description, :skills, :experience, :location, :company_name)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/candidates/new.html.erb
<h1>SignUP Now!!</h1>
<%= form_for @candidate do |c| %>
  <%= c.label :first_name %><br>
  <%= c.text_field :first_name %><br>
  <%= c.label :last_name %><br>
  <%= c.text_field :last_name %><br>
  <%= c.label :email %><br>
  <%= c.text_field :email %><br>
  <%= c.label :password %><br>
  <%= c.password_field :password %><br>
  <%= c.label :confirm_password %><br>
  <%= c.password_field :confirmation_password %><br>
  <%= c.submit  %>
<% end %>

app/views/candidates/profile.html.erb
<h1>Candidate Profile</h1>


<%= @candidate.first_name %>&nbsp &nbsp
<%= @candidate.last_name %>&nbsp &nbsp
<%= @candidate.email %>&nbsp &nbsp
<%= link_to 'signout', candidates_signout_path %>
<hr>
<br>
<h3> Total No of Applied Jobs </h3>

<%=  @jobs_count %>

app/views/candidates/signin.html.erb
<div class="container">    
  <div id="loginbox" style="margin-top:50px;" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
    <div class="panel panel-info">
      <div class="panel-heading">Login Now</div>
      <div class="panel-body">
        <%= form_for(:candidate, class: "form-horizontal") do |c| %>
          <div class="form-group">
            <label for="exampleInputEmail1">Email address</label>
            <%= c.text_field :email, class: "form-control", placeholder: "Enter Email" %>
          </div>
          <div class="form-group">
            <label for="exampleInputEmail1">Password</label>
            <%= c.password_field :password, class: "form-control", placeholder: "Enter Password" %>
          </div>
          <div class="form-group">
              <%= c.submit "Login", class: "btn btn-primary pull-right" %>
          </div>
        <% end %>
      </div> 
    </div>
  </div>
</div>

app/views/candidates/signup.html.erb
<div class="container">
  <div id="signupbox" style="margin-top:50px" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
    <div class="panel panel-info">
      <div class="panel-heading">SignUP Now!!</div>
      <div class="panel-body">
          <%= form_for(:candidate, :url=>{:controller=>"candidates", :action=>"signup_create"}, :method => :post, class: "form-horizontal") do |c| %>
            <div class="form-group">
              <label for="firstName">First Name</label>
              <%= c.text_field :first_name, class: "form-control", placeholder: "Enter first name" %>
            </div>
            <div class="form-group">
              <label for="lastName">Last Name</label>
              <%= c.text_field :last_name, class: "form-control", placeholder: "Enter last name" %>
            </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Email address</label>
              <%= c.text_field :email, class: "form-control", placeholder: "Enter Email" %>
            </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Password</label>
              <%= c.password_field :password, class: "form-control", placeholder: "Enter Password" %>
            </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Re Enter Password</label>
              <%= c.password_field :password_confirmation, class: "form-control", placeholder: "Re Enter Password" %>
            </div>
            <div class="form-group">
              <%= c.submit "signup", class: "btn btn-primary pull-right" %>
            </div>
          <% end %>
        </div>
    </div>
  </div>
</div>

app/views/jobs/index.html.erb
<div class="container">
<%= render "shared/search" %>
  <div class="panel panel-info">
    <div class="panel-heading">List Of Jobs</div>
      <div class="panel-body">
      <% @jobs.each do |job| %>
        <div class="row">
          <div class="col-lg-12"><h4 style="padding:5px;"><%= link_to job.title, job_path(job.id) %></h4></div>
          <div class="col-lg-12">
            <div class="col-lg-2">
              skills:
            </div>
            <div class="col-lg-4">
              <%= job.skills %>
            </div>
            <div class="col-lg-2">
              Experience:
            </div>
            <div class="col-lg-4">
              <%= job.experience %>yrs
            </div>
          </div>
          <div class="col-lg-12">
            <div class="col-lg-2">
              Location:
            </div>
            <div class="col-lg-4">
              <%= job.location %>
            </div>
            <div class="col-lg-2">
              Company:
            </div>
            <div class="col-lg-4">
              sekhar systems pvt Ltd
            </div>
          </div>
         </div>
        <% if @candidate.present? %>
          <% if(@candidate.applied_job(job.id)) %>
            <%= link_to 'Applied' %>
          <% else %>
            <%= link_to 'Apply', apply_job_candidate_path(job.id, session[:candidate]), method: :post, :id=>"apply" %>
          <% end %>
        <% end %><hr>
      <% end %>  
    </div>
  </div>
</div>

app/views/jobs/new.html.erb
<div class="container">
    <div class="panel panel-info">
      <div class="panel-heading">New Job</div>
      <div class="panel-body">
        <%= form_for @job, class: "form-horizontal" do |job| %>
          <div class="form-group">
            <label for="title">Title</label>
            <%= job.text_field :title, class: "form-control", placeholder: "Please Enter Job Title"%>
          </div>
          <div class="form-group">
            <label for="description">Descrioption</label>
            <%= job.text_area :description, placeholder: "Please Enter Job Description", style: "margin: 0px 0px 10px; width: 1110px; height: 98px;"%>
          </div>
          <div class="form-group">
            <label for="skills">Skills</label>
            <%= job.text_field :skills, class: "form-control", placeholder: "Please Enter skills"%>
          </div>
          <div class="form-group col-lg-6">
            <label for="experience">Experience</label>
            <%= job.text_field :experience, class: "form-control span4", placeholder: "Please Enter Experience"%>
          </div>
          <div class="form-group col-lg-6">
            <label for="location">Loacation</label>
            <%= job.text_field :location, class: "form-control span4", placeholder: "Please Enter Location"%>
          </div>
          <div class="form-group">
            <label for="company">Company Name</label>
            <%= job.text_field :company_name, class: "form-control", placeholder: "Please Enter skills"%>
          </div>
          <div class="form-group">
            <%= job.submit 'create job', class: "btn btn-primary pull-right" %>
          </div>
        <% end %>
      </div>
    </div>
</div>

app/views/jobs/show.html.erb
<div class="container">
  <div class="panel panel-info">
      <div class="panel-body">
        <div class="row">
          <div class="col-lg-12"><h2><%= @job.title %></h2></div>
          <div class="col-lg-12">
            <%= @job.description %>
          </div><br>
          <div class="col-lg-12">
            <div class="col-lg-2">
              skills:
            </div>
            <div class="col-lg-4">
              <%= @job.skills %>
            </div>
            <div class="col-lg-2">
              Experience:
            </div>
            <div class="col-lg-4">
              <%= @job.experience %>yrs
            </div>
          </div>
          <div class="col-lg-12">
            <div class="col-lg-2">
              Location:
            </div>
            <div class="col-lg-4">
              vishakapatnam
            </div>
            <div class="col-lg-2">
              Company:
            </div>
            <div class="col-lg-4">
              sekhar systems pvt Ltd
            </div>
          </div>
         </div>
        <% if @candidate.present? %>
          <% if(@candidate.applied_job(job.id)) %>
            <%= link_to 'Applied' %>
          <% else %>
            <%= link_to 'Apply', apply_job_candidate_path(job.id, session[:candidate]), method: :post, :id=>"apply" %>
          <% end %>
        <% end %>  
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <a class="brand active" href="/">JobsAdda</a>
    <ul class="nav navbar-nav pull-right">
        <li class="active"><%= link_to 'Home', "#" %></li>
        <li><%= link_to 'Jobs', jobs_path %></li>
        <li><%= link_to 'AboutUs', "#" %></li>
        <li><%= link_to 'ContactUs', "#" %></li>
          <% if session[:candidate].present? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
             Profile 
             <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><a href="/candidates/profile">User Profile</a></li>
              <li><a href="/candidates/signout">Sign Out</a></li>
            </ul>
          </li>
        </ul>
          <% else %>
            <%= link_to "Sign in", signin_path, class: "btn btn-success pull-right" %>
          <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JobsAdda</title>
  <%= stylesheet_link_tag    'application', media: 'all'  %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tag %>
</head>
<body>
  <section id="container">
    <%= render 'layouts/header'%>
    <section id="main-content">
      <section class="wrapper" >
        <!-- page start-->
          <%= yield %>
        <!-- page end-->
      </section>
    </section>
    <%= render "layouts/footer"%>
  </section>
</body>
</html>

app/views/shared/_search.html.erb
<div class="search">
  <form class="form-horizontal">
    <div class="from-group">
    <input type="text" class="form-control span3" placeholder="search by skills">
    <input type="text" class="form-control span3" placeholder="search by Location">
    <input type="text" class="form-control span3" placeholder="search by Experience">
    <button class="btn btn-info">Search Here</button>
  </form>
</div>